spring:
  application:
    name: bpm-external-service
  cloud:
    config:
      username: configserver
      password: configserver@datis!
  config:
    import: "optional:configserver:http://config-server"
  profiles:
    default: dev
---

spring:
  config:
    activate:
      on-profile: dev
  jackson:
    default-property-inclusion: non_null

service:
  system:
    user: admin
    pass: admin@qwer!
  api: /api
  client:
    timeout: 60000
    base-url: http://bss-dev.sf.faraborddi.dc

server:
  port: 7030